name: Deploy Weather App

on:
  push:
    paths:
      - 'projects/weather-app/**'          # run when code here changes
      - '.github/workflows/weather.yml'    # …or when this workflow itself changes

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: projects/weather-app  # all run steps execute here

    steps:
      # 1. Check out code
      - uses: actions/checkout@v4

      # 2. Set up Node (matches your local version)
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install & build
      - run: npm ci
      - run: npm run build

      # 4. Copy the fresh dist/ into the repo *
      - name: Copy build to project sub-folder
        run: |
          rm -rf ../../projects/weather-app/*
          cp -r dist/* ../../projects/weather-app/

      # 5. Commit the built files back to main (skip a loop with [skip ci])
      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ../../projects/weather-app/*
          git commit -m "chore: update weather-app build [skip ci]" || echo "No changes"
          git push
