name: Deploy Weather App

on:
  push:
    paths:
      - 'projects/weather-app/**'
      - '.github/workflows/weather.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Grant write permissions to the GITHUB_TOKEN
      contents: write

    defaults:
      run:
        working-directory: projects/weather-app

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Inject VITE_WEATHER_KEY secret
        run: echo "VITE_WEATHER_KEY=${{ secrets.VITE_WEATHER_KEY }}" >> $GITHUB_ENV

      - run: npm ci
      - run: npm run build

      - name: Copy build output to tracked folder
        run: |
          # This step seems redundant as the build output is already in the repo structure.
          # Consider if you really need to copy files that are already in place.
          # If the build output is inside `projects/weather-app/dist`, you can directly commit from there.
          cp -r dist/* ../../projects/weather-app/dist/

      # 5 Commit & push only the built files (no copy step needed)
      - name: Commit and push build
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/*
          git commit -m "chore: update weather-app build [skip ci]" || echo "No changes to commit"
          git push